version: "3.9"
services:

  development:
    image: python:3.9-slim-buster
    build:
      context: .
      target: development
    ports:
      - "5001:5000"
    volumes:
      - ./todo_app:/app/todo_app
    env_file: .env
