version: "3.7"
services:

  development:
    build: 
      context: "."
      target: development
    image: todo-app:dev
    container_name: todo_app_dev
    ports:
      - "5001:5000"
    env_file:
      - .env
    # want to mount the current directory so we can make code changes
    volumes:
      - type: bind
        source: ./
        target: /usr/src/todo_app
