name: Continuos Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  schedule:
    - cron: '40 8 * * *' 
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: Build docker
        run: docker build --target testing --tag todo-app:testing .
      - name: Run tests
        run: docker run --env-file ./.env.test todo-app:testing
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          user: $DOCKER_HUB_USER
          password: $DOCKER_HUB_TOKEN  
  publish:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/exercise-8')
    name: push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: build docker
        run: docker build --target production --tag /todo-app:production-${{ github.sha }} .
      - name: Push to docker hub
        run: docker push $DOCKER_HUB_ACCESS_USER/todo-app:production-${{ github.sha }}
    needs: build
