name: Continuos Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  schedule:
    - cron: '40 8 * * *' 
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: Build docker
        run: docker compose up testing --exit-code-from testing

  publish:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/exercise-8')
    name: push to docker hub  
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build docker
        run: docker build --target production --tag /todo-app:prod-${{ github.sha }} ..
      - name: Push to docker hub
        run: docker push $DOCKER_HUB_ACCESS_USER/todo-app:prod-${{ github.sha }}
    needs: build
