name: Continuos Integration
on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
    - name: Docker build
      uses: actions/checkout@v2
      run: docker build --target testing --tag todo-app:testing .
    - name: Run tests
      uses: actions/checkout@v2
      run: docker run --env-file ./.env.test todo-app:testing
