name: Continuos Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  schedule:
    - cron: '40 8 * * *' 
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: Build docker
        run: docker build --target testing --tag todo-app:testing .
      - name: Run tests
        run: docker run --env-file ./.env.test todo-app:testing

  publish:
    env:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_ACCESS_USER }}
      TF_VAR_client_id: ${{ secrets.TF_VAR_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.TF_VAR_CLIENT_SECRET }}
      TF_VAR_SECRET_KEY : ${{ secrets.TF_VAR_SECRET_KEY }}
      TF_VAR_azure_client_secret: ${{ secrets.TF_VAR_ARM_CLIENT_SECRET }}
      TF_VAR_azure_client_id: ${{ secrets.TF_VAR_ARM_CLIENT_ID }}
      TF_VAR_azure_subscription_id: ${{ secrets.TF_VAR_ARM_SUBSCRIPTION_ID }}
      TF_VAR_azure_tenant_id: ${{ secrets.TF_VAR_ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}  
    if: (github.event_name == 'push' && github.ref == 'refs/heads/exercise-12')
    name: push to docker hub  
    runs-on: ubuntu-latest  
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd        
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: build docker
        run: docker build --target production --tag ${{ secrets.DOCKER_HUB_ACCESS_USER }}/todo-app:prod-latest .
      - name: Push to docker hub  
        run: docker push ${{ secrets.DOCKER_HUB_ACCESS_USER }}/todo-app:prod-latest
      - name: Terraform init
        run: |
          terraform init
      - name: Deploy app with terraform
        run: terraform apply -auto-approve
      - name: Re-pull and restart the app in azure
        run: curl -dH -X POST "$(terraform output -raw cd_webhook)" --fail
    needs: build
