name: Continuos Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  schedule:
    - cron: '40 8 * * *' 
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: Build docker
        run: docker build --target testing --tag todo-app:testing .
      - name: Run tests
        run: docker run --env-file ./.env.test todo-app:testing

  publish:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/exercise-8')
    name: push to docker hub  
    runs-on: ubuntu-latest  
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: build docker
        run: docker build --target production --tag ${{ secrets.DOCKER_HUB_ACCESS_USER }}/todo-app:prod-${{ github.sha }} .
      - name: Push to docker hub  
        run: docker push ${{ secrets.DOCKER_HUB_ACCESS_USER }}/todo-app:prod-${{ github.sha }}
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
            machine git.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          EOF
      - name: Add Heroku remote
        run: heroku git:remote --app ${{ secrets.HEROKU_APP_NAME }}
      - name: Login into Heroku's registry
        run: heroku container:login
      - name: Tag for heroku
        run: docker tag ${{ secrets.DOCKER_HUB_ACCESS_USER }}/todo-app:prod-${{ github.sha }} registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: Push to heroku
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: Release heroku
        run: heroku container:release web
    needs: build
