name: Continuos Integration
on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker-compose up testing
    - run: docker build . --target  testing && docker run todo-app:testinng