name: Continuos Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: Build docker
        run: docker build --target test --tag todo-app:testing .
