name: Continuos Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  schedule:
    - cron: '40 8 * * *' 
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: Build docker
        run: docker build --target testing --tag todo-app:testing .
      - name: Run tests
        run: docker run --env-file ./.env.test todo-app:testing

  publish:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/exercise-9')
    name: push to docker hub  
    runs-on: ubuntu-latest  
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: build docker
        run: docker build --target production --tag ${{ secrets.DOCKER_HUB_ACCESS_USER }}/todo-app:prod-latest .
      - name: Push to docker hub  
        run: docker push ${{ secrets.DOCKER_HUB_ACCESS_USER }}/todo-app:prod-latest
      - name: Azure restart and pull the latest version of docker container
        run: curl -dH -X POST 'https://\$bearsxapp:$AZURE_PASSWORDbearsxapp.scm.azurewebsites.net/api/registry/webhook' --fail
    needs: build

